---
title: "Using the interactive GUI - sdcGUI"
author: "Bernhard Meindl"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 5
    number_sections: false
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction and Main Features
Package `sdcMicro` contains a [shiny](https://cran.r-project.org/web/packages/shiny/index.html) app that should help users that are non-experts in R (command-line) to apply disclosure limitation techniques. For this reason, users may upload (micro)data files from different software products into the app and then start to anonymize the dataset by working within the interactive, graphical user interface (GUI). This document will give an overview of the functionalities of the graphical user interface which can be started with `sdcGUI()`. The main functionality of the GUI is:

- Uploading microdata
- Modify and analyze microdata
- Creating `sdcMicroObj`-instances
- Perform anonymization techniques on an `sdcMicroObj`-problem instance
- Obtain information on disclosure risks and/or information loss
- Keep reproducibility by being able do download the underlying code from `sdcMicro`

We now describe the features of the interactive graphical user interface in detail. The GUI is seperated into 7 main categories, which can be selected from the navigation bar at the top of the screen. Initially, some of these pages will be empty and their content changes once microdata have been uploaded or an `sdcMicroObj` has been generated.

# About/Help {#about}

to be written

# Microdata {#microdata}
On this page, the user has the possibility to either upload data sets stored as files on the hard drive into the GUI or to select data frames that exist in the users workspace before working the graphical user interface was started. This allows to perform common datamanipulation steps directly in `R` before continuing to anonymize the dataset using the GUI.

We note that the content of this pages changes depending if micro data have already been uploaded or not. In the former case, the user can view, modify or reset variables from the uploaded dataset as described in chapter  [Modify microdata](#modify_microdata). In the latter case, the user is asked to upload data in the GUI which is described in chapter [Upload microdata](#upload_microdata) below.

## Upload microdata {#upload_microdata}
By default, no microdata are loaded into the GUI. Therefore the user has to upload some data in the GUI that can later be anonymized. If no microdata are available, the left-sidebar shows the following options that can be selected by clicking on the appropriate radio-button entry. In case the selected data could not be used (eg. the data could not be converted to a `data.frame`), the user is presented with the resulting error message and a button `Try-again`. After clicking this button, another microdata file can be imported.

### Use testdata/internal data
This screen allows the user to select data.frames that are available in the users-workspace when starting the user interface. Two test-data sets (`testdata` and `testdata2`, information on which is available from `?testdata`) that are included in `sdcMicro` are always available. Pressing the action button below the drop-down selection input will make the GUI use the selected data frame.

### R-Dataset (.rdata)
Here users can opt to upload a file saved in `R` binary format. The users can change the options if character vectors should be automatically converted to factors and if variables that only contain missing-values only should be dropped. By clicking on the `Browse` button the user needs to select a `rdata`-file on disk which he wants to upload. For detailed explanation on the options, please see the chapter on [additional options](#additional_options).

### SPSS-File (.sav)
Here users can opt to upload a file exported from `SPSS`. The users can change the options if character vectors should be automatically converted to factors and if variables that contain only missing-values ('NA') only should be dropped. By clicking on the `Browse` button the user needs to select a `sav`-file on disk which he wants to upload. For detailed explanation on the options, please see the chapter on [additional options](#additional_options).

### SAS-File (.sasb7dat)
Here users can opt to upload a file exported from `SAS`. The users can change the options if character vectors should be automatically converted to factors and if variables that contain only missing-values ('NA') only should be dropped. By clicking on the `Browse` button the user needs to select a `sas7bdat`-file on disk which he wants to upload. For detailed explanation on the options, please see the chapter on [additional options](#additional_options).

### Comma-seperated File (.csv, .txt)
Here users can opt to upload a text file where variables are seperated by some characters. Typically these data would be exported from software such as `Excel`. It is crucial that users choose if the data file has variable names in the first row and how variables are seperated. Then users may also change if character vectors should be automatically converted to factors and if variables that contain only missing-values ('NA') only should be dropped when the data are read into the GUI. By clicking on the `Browse` button the user needs to select a `txt` or `csv`-file on disk which he wants to upload. For detailed explanation on the options, please see the chapter on [additional options](#additional_options).

### STATA-File (.dta)
Here users can opt to upload a file exported from `Stata`. The users can change the options if character vectors should be automatically converted to factors and if variables that contain only missing-values ('NA') only should be dropped. By clicking on the `Browse` button the user needs to select a `dta`-file on disk which he wants to upload. For detailed explanation on the options, please see the chapter on [additional options](#additional_options).

### Additional options {#additional_options}
We now describe the choices users can make when uploading data.

**Convert character-vectors to factors?**

This option not available when an existing data frame from the current workspace should be used. For any other selection, this radio button input has two possible choices, `TRUE` (the default value) and `FALSE`. If `TRUE`, any variables that are read into `R` as character-vectors should be automatically converted to a factor variable. Each distinct value of the variable will be a factor level in the imported dataset. If `FALSE`, no conversion is applied. 

**Drop variables with only NA-values**

This option not available when an existing data frame from the current workspace should be used. For any other selection, this radio button input has two possible choices, `TRUE` (the default value) and `FALSE`. If `TRUE`, any variables in which only `NA`-values are read in are removed from the data set. If this option is set to `FALSE`, these variables (if any) will not be dropped.

**First row contains variable names**

This option not only available when a text/csv file should be imported. In that case, this radio button input has two possible choices, `TRUE` (the default value) and `FALSE`. If `TRUE`, the first row of the imported data set will be interpreted as variable names, if `FALSE`, variable names are automatically generated.

**Separator (Semicolon, Tab, Colon)**

This option not only available when a text/csv file should be imported. In that case, this radio button input has three possible choices, `Semicolon` (the default value), `Tab` and `Colon` defining the value that is used to seperate variables in the input file.

- `Semicolon`: the `;` character is used as seperator
- `Tab`: tabulators (`\t`) are used as seperators
- `Colon`: the ``r dQuote(",")`` character is used as seperator

**Select File Input:**

This option not available when an existing data frame from the current workspace should be used. For any other selection, clicking on the `Browse` button allows the user to select a file on the local hard drive. A feature is that only files with the accepted file ending (e.g `.dta` when files from `Stata` `.rdata` when data exported from `R` should be imported) are shown. This reduces the risk, that a unsuitable file can be selected. Once a file has been selected, pushing the `Open` button immediately uploads the file so that the GUI can process it. If the file cannot be read into the system successfully, the user is presented with the resulting error message. If everything works out smoothly, microdata are now available and the left sidemenu changes. The user can now start the anonymization process. For further information, please have a look at the following sections.

## Modify microdata {#modify_microdata}
Once data have been uploaded, the content of the *Microdata*-page changes and users can select from a range of possibilities on what to do with the current inputdata. Once data are available, a button `Reset inputdata` is available on top of the sidebar. Clicking this button allows to reset or delete the current input data. However, clicking this button does not immediately reset the problem. Instead, a pop-up window comes up where the user has to confirm to reset the current microdata. This action will be performed, if the user click on the button labelled `Delete current inputdata`. If the user clicks `Dismiss`, the inputdata remains unchanged.

Below this button, a list of radio buttons termed `What do you want to do?` is shown. By default, the first entry ("*Display Microdata*") is selected. These entries can be selected by clicking on the desired text or directly on the button. We now continue to describe the features that can be selected.

### Display Microdata {#display_microdata}
This is the default selection, after microdata have been successfully imported or uploaded as described in [uploading microdata](#upload_microdata). This page gives a short overview on the microdata. It shows the name of the imported file as well as the number of observations and the number of variables that are available. Below this information, the user is presented with an interactive table containing the current microdata. The variables can be sorted by clicking on the small arrows next to the variable names on top of the table. Also on the top, there is a dropdown field where users can select how many observations should be displayed on one page. On the bottom of the table the users can find a dynamic pagination field which allows users to jump to a given *"page"* of the current table.

### Explore variables {#explore_inputvars}
On this page users have the possibility to explore variables from the current microdata. Users have to choose a variable by selecting a variable from the dropdown field with label *"Choose a variable"*. The default value of this input field is the first variable in the dataset. Optionally, a second variable can be selected by choosing a variable from the dropdown field labelled *"Choose a second variable (optional)"* which has the default value of *"None"*. Once the variables have been selected, a graph and additional information is presented below. The specific output depends on the number of variable(s) chosen as well as their type:

**One variable selected:**

- the selected variable is of type `factor` or `character`: 

In this case, a barplot of the factor levels is shown. Below that, a table showing for each factor level the level itself, how often it occurs and the corresponding percentage is shown. Below that, again the number and percentage of missing values is shown.

- the selected variable is of type `integer` or `numeric`:

In this case, a histogram of the selected variable is shown. Below the graph, a table showing main summary statistics (Minimum, Mean, Median, Maximum and 5%-, 25%-, 75%- and 95%-quantiles) are shown. Below this table, the number and percentage of missing values is displayed.

**Two variables selected:**

- Both variables are of type `integer` or `numeric`:

If both selected variables are continuous (`numeric` or `integer`), a scatterplot of the two variables is displayed. Below that, the correlation coefficient (Pearson) using only pairwise complete observations between the two variables is listed. Below that, two tables are shown. Each table shows the main summary statistics for one of the selected variables. The information included in the tables are (as in the case when only one continuous variable is selected) the Minimum, Mean, Median, Maximum and 5%-, 25%-, 75%- and 95%-quantiles of the variable. Finally, information on the number and percentage of missing values is shown for both variables.

- Both variables are of type `factor` or `character`:

In this case, a mosaicplot of the selected variables is shown as well as a table, containing a cross-tabulation of each levels (or unique values in case of a character input) that shows the number of percentages of each combination of codes given the two selected variables including any combinations with `NA`. Below this table, the number and percentage of missing values is displayed for both selected variables.

- One variables is of type `factor` or `character`, the other variable is of type `integer` or `numeric`:

In this case, a grouped boxplot of the continous variable (type is `integer` or `numeric`) is shown for each level or unique value of the non-continuous variable. Below, for each level of the non-continuous variable, the same summary statistics as already described above of the continuous variable are shown. Finally, the number and percentage of missing values is displayed for both selected variables.

### Reset variables {#reset_inputvars}
When a microdata set is uploaded, internally a backup of the unmodified dataset is saved. This allows users to reset any modifications in variables in the inputdata file which can be done on this page. To do so, the user needs to select one or more variables from the select field which is by default empty. When all variables that should be reverted are selected, one has to click outside the dropdown field to close the input. Afterwards, an action button labelled `Reset selected variable(s) to their original state` occurs below the input field. Clicking on this button resets the selected variables to their original state. In case you want to remove already selected variables, you can just click on these variable names in the input field and either press the *"backspace"*- or *"delete"*" keys on the keyboard.

In any case, after pressing the action button, the GUI changes to the [*"Explore variables"*](#explore_inputvars) page at which the first of the selected variable(s) is shown.

### Use only a subset of the available microdata
On this page it is possible to decrease the size of the inputdata. This is especially useful if one wants to test different parameter settings and a run on the complete dataset would take long. To reduce the size of the inputdataset, the user has to select a method using the drop down field `How would you like to restrict the microdata?` and to select a value from the slider `Choose your 'n'`. The following choices are possible on how to reduce the dataset, the range of values that can be chosen from the slider depends on the choice.

  - `n-Percent of the data`: `n%` of the data will be randomly chosen. The slider ranges in this case from 1 to 100.
  - `the first n-observations`: the data set is decreased by only using the first `n%` records. The slider ranges in this case from 1 to the total number of records.
  - `every n-th observation`: This choice allows to create a simple, systematic sample of input data by selecting every `nth` observation. The slider ranges in this case from 1 to at max 500.
  - `exactly n randomly drawn observations`: the data set is decreased by taking a random sample of `n%` records. The slider ranges in this case from 1 to the total number of records.
    
When the desired selections have been applied, pushing the button `Apply subsetting of the microdata` performs the actual sub-subsampling. After the micro data set has been reduced, the user is taken to the [Display microdata](#display_microdata) page where the reduced dataset can be analysed.

### Convert numeric variables to factors
This page allows to convert continuous variables (`numeric` or `integer`) into factors. Users can choose from a range of possibilites how the factor variable should be generated, ranging from automatic conversion to complete manual control. 

By default, two input fields are available. On the left hand side there is a dropdown select field termed `Choose numeric variables` where the user can select from the list of numeric variables in the input data set. Next to this element, there is are two radio buttons labelled `Use custom breaks?` with two options, `no` (the default) and `yes`. If the `no` is selected in this input and at least one numeric variable has been clicked from the select input `Choose numeric variables`, a button termed `Convert to factor(s)` occurs. Pressing this button converts all of the selected numerical variables into factors. Afterwards, the user is taken to the [explore variables](#explore_inputvars) page where the first of the selected variable(s) is shown.

If, however, the radio buttons `Use custom breaks?` are set to `yes`, the layout of the page changes. In this case, the user is able to adjust the way the factor variable should be generated and additional UI elements appear. The first visible change is, that only one numeric variable can now be selected. Now, a list of radio buttons labelled `Choose a numeric variable` is shown where all available variables are printed below each other. Selecting a specific variable works by clicking on either the variable name or the radio button itself. The next choice the user has to make is in a select input field termed `Select Algorithm` in which `equidistant` (the default), `logEqui`, `equalAmount` or `manual` are possible values.

The remaining user interface is the same for the first three choices of the `Select Algorithm` input and is slightly different if `manual` has been selected. In the first case, a numeric input field labelled `Specify the number of breaks` is shown while in the second case a text input field labelled `Specify the custom breaks` occurs right next to the select input field where the algorithm can be selected. 

If either `equidistant`, `logEqui` or `equalAmount` are selected, the number specified in the numeric input field defines the number of levels the new factor will have. The difference between the methods are:

- `equidistant`: the intervals used for the recoding have (approximately) the same size
- `logEqui`: the intervals used for the recoding of the log-transformed data have (approximately) the same size
- `equalAmount`: the intervals used for recoding are chosen in a way, that the new groups include (approximately) the same number of observations 

If `manual` was specified in the select input termed `Select Algorithm`, the user can enter custom breakpoints that will be used to define the new groups in the recoded variable. The syntax in this text field is the way that the breakpoints (numbers) have to be entered seperated by a colon (`,`). This sequence of numbers will be interpreted as follows: all values greater than the value before a colon and all values smaller or equal than the value after the colon are grouped together. Any non-matched values will be `NA`. As an example, entering `1,3,5,9` would create a factor from a numeric variable by grouping together all values in x greater than 1 and less or equal to 3 into the first group, all values greater than 3 and less or equal to 5 into the second group and all values greater than 5 and less or equal to 9 into a third group. Any values in x less or equal than 1 or greater or equal to 10 would be `NA`. However, `-Inf` and `Inf` may be entered as the first or last value to avoid the generation of `NAs`. Already existing missing values in the numeric input variable will stay `NA` after the recoding.

What is common for all choices of `Select Algorithm` is that a button labelled `Convert to factor` appears if the information that has been entered is correct. Also, at the bottom of the page a table with two columns is shown. The first columns shows each of the unique values of the selected variable while the second column shows the number of occurances of this value. On pressing the action button, the selected numeric variable is recoded according the the parameters that have been chosen. After the recode has been done, the current view changes to the [explore variable](#explore_inputvars) page with the recoded factor variable already being selected.

### Convert variables to numeric
In this page, factor variables from the input data may be converted back to numeric variables. If no factor variables are present in the micro data, the user is shown this information and no conversion is possible. If, however, factor variables are available from the current active micro data, the user can select one or more variables from the input field labelled `Choose variable`. Once at least one variable is selected, a button called `Recode to numeric` occurs below the variable selection input. After clicking this button, the conversion is done and the view changes to the [explore variable](#explore_inputvars) page with the first of the recoded variables being selected.

It should be noted however - as also shown on the GUI - that this feature should be used with care because internalle function `as.numeric()' is used to perform the conversation. Thus, the resulting numeric vector contains the underlying numeric (integer) representation of the input factor, which is often meaningless as it may not correspond to the factor levels.

### Modify an existing factor-variable {#recode_factors_inputdata}
When this option has been selected from the left hand sidebar, it is possible to modify existing factor variables. The most common use case is to combine one or more levels of the factor. The other use case is to rename single factor levels. In order to proceed, the user must first select an existing factor variable from the select input labelled `Choose factor variable`. Next to this box, there is another input termed `Select Levels to recode/combine`. In this input, all the levels of the active factor variable can be choosen by clicking on the are selectable. Already selected levels may be removed again by clicking on them with the mouse and pressing either the *"backspace"*- or *"delete"* keys on the keyboard.

If at least one factor level is selected, a text input called `New label for recoded values` is shown. By default, this input has a value that is computed by joining the selected factor levels together using the character `_` as seperator. By clicking into this text field, users can also start to enter a custom name for the new factor level. If only one level has been selected in `Select Levels to recode/combine`, entering a value different than the default value in this input leads to renaming of this specific factor level. 

Below this three input fields a button labelled `Update factor variable` and a barplot showing the absolute number of the current levels of the factors are shown. Pressing the action button results in updating the factor. In this case, the page refreshes and the plot adjusts the the changes that have been applied.

### Create a stratification variable {#create_strata_var}
On this page, the user is able to generate a new variable based on two ore more variables from the current micro data. The reason for this is that several anonymization techiques that are explained [here](#anonymize_categorical) and [here](#anonymize_numerical) can by applied independently to subgroups of the input data that are given by the values of a so called `stratification variable`. This page allows to create such a variable in a convinient way.

The user has to specify at least two variables in the select field labelled `Select Variables`. From this field, all variables that are available in the micro data set can possibly be selected. Once two or more variables are selected, two new inputs appear. The first one appears right next to the variable selection field and is called `New variable name`. In this field, user can enter a desired name for the new variable. By default, the variable name listed consists of the selected variables chained together using `_` as seperator. By clicking into the field, the user can enter a customized variable name. If the current value in this text input field is not the name of an already existing variable, a button termed `Create stratification variable` appears below. Clicking on this button adds the new variable to the input data set. The variable is generated as a factor variable in which the values of the contributing variables are also chained together using `_` as the seperator. After pressing the button, the page changes to the [explore variable](#explore_inputvars) page where the newly generated variable is already selected.

### Set specific values in a variable to `NA`
In this section, users can set values in some variables to missing (`NA`). The first step is to choose one of two possible methods by choosing either `by Id` (the default selection) or `by rule` in the radio button input labelled `How do you want to select the Observations where you want to set values to missing?` on top of the page.

If `by Id` has been selected, the user can set values in one or more variables for a specific record to missing. He therefore needs to select at least one variable in the input called `Select Variable for Suppression`. Once at least one variable has been selected, a new input field occurs. In this input called `In which ID do you want to suppress values?`, a number between 1 and at most the number of records can be specified. This selection refers to the row in which for the selected variables the values will be set to `NA`. The user can change this index either by clicking on the small arrows at the right hand side of the input field which allow to increment or decrement the current number by one. As an alternative, it is also possible to directly enter a number in the field.

In case `by rule` has been selected, these choices are slightly different. In the variable selection it is only possible to select one variable. The other difference is that there is no input field where the user can select a number. Instead, there is a dropdown field where the user can select one of the distinct values of the selected variable. The idea is that all records having this values in the selected variable will the set to `NA`.

The remaining part of this page is identical for both choices of the method. Below these inputs, an interactive table showing the current microdata is shown. This table can be filtered and navigated exactly the same way as already described [here](#display_microdata). If all selections are valid, a button labelled `Set values to NA` is shown above this table. Pressing this button sets the correspondig values to `NA` in the micro data. Afterwards, the page changes and the  [Exlore variables](#explore_inputvars) page is shown. In this page, the (first) selected variable in which values should be set to missing is pre-selected to be analyzed.

### Hierarchical data
In this page, users find the functionality to deal with hierarchical data. The idea is as follows. Often data contain clusters, eg. individual within households or students within classes. In this case, it is often the case that some variables of the data set are only relevant on cluster-level while others are relevant on individual level. It is also often the case that one wants to apply different anonymization strategies for the different *levels* of the data. So the GUI offers a way to deal with this situation in the following way.

The radio buttons labelled `What do you want to do?` allow to choose from `Prepare file for the anonymization of household level variables` (the default) and `Merging an anonymized household level file`. In the former case, the uploaded micro data set can be restricted to those variables relevant for the cluster-level only. Once that has been done, the user may anonymize the household file and can finally export the anonymized file to disk as described [here](#export_data). In the latter case, an already exported, anonymized household-level file can be imported to the GUI and merged with the individual level file. Then the anonymization process can be started by creating a problem instance using individual-level variables as keys. Finally, the user is able to export an anonymized file that is safe on both levels. We now describe both possibilibies in this section:

**Prepare file for the anonymization of household level variables**

In case the goal is to prepare a household-level file, the user first needs to select an identifier for the households or clusters. This select input termed `Please select a suitable household identificator` is initially empty. Once a variable has been selected from the list of all variables available from the input data, an additional select field called `Please select all variables that refer to households and not to individuals` appears next to it. In this input, one or more variables that are relevant for households only (that means, these variables feature the contain the same values for each household) can be selected. Once at least one additional variable has been chosen, a button labelled `Create household-input data` is shown below. Clicking on this button restricts the current data set to the selected variables and to only one (the first) record for each value of the cluster identificator. Finally, the page refreshes and the number of observations and variables in the updated, household level data set is shown. Additionally, the names of the variables as well as their type are presented in tabular format.

**Merging an anonymized household level file**

In this case, the goal is to merge an already anonymized household level file to the currently available data file. This procedure is performed in two steps. In the first step, the user needs to click on the `Browse` button to select the anonymized file that should be merged. Once the `Open` button is clicked the file is uploaded immediately. We note here that it is only possible to upload data that have been exported as `.rdata`-files as described [here](#export_data). After pressing the button, the file will be uploaded to the system. If an error occured (e.g the selected data file does not contain a data frame or if the data set does not contain any variables that overlap with the current inputdata) an error message is shown and the user may upload a different file from disk.

On success, the layout of the page changes too. A button labelled `Reset uploaded household data` appears which allows to reset the household level data and makes it possible to upload yet another file. Additionally, a dropdown field labelled `Select a variable containing household ids` appears. In this input, the user needs to select a variable from the list of variables that are available from both datasets containing the identification variable. The selected variable will finally be used to merge the datasets. Below this selection, a button termed `Merge household- and individual level data` is shown. On clicking this button, the merge is performed. If everything went well, the page refreshes and the number of observations and variables in the updated micro data file shown. Additionally, the names of the variables as well as their type are presented in tabular format.

# Anonymize {#anonymize}
This page is relevant for either creating a sdc problem (of class `sdcMicroObj`) that can then be anonymized within the GUI. If the user navigates to this page and no inputdata have been uploaded, this page shows two options. The user can either click on the button labelled `Upload microdata` or on a button labelled `Upload a previously saved sdc problem`. In the first case the user is taken to the [Microdata](#microdata) page where microdata can be uploaded as described [here](#upload_microdata), in the latter case the user is taken to the [Undo](#undo) page where an already [exported problem instance](#export_sdc_probleminstance) can be uploaded.

If Microdata are available and no problem has been defined, the user can define a new sdc problem instance. Details on how to this can be done are given in chapter [Set up a problem](#setup_sdcproblem). Once a problem instance has been defined, the page layout changes and the user can either view or modify the problem instance as described in []() or apply anonymization techniques to [categorical](#anonymize_categorical) or [continuous](#anonymize_numerical) variables. Details on how specific methods can be applied are given in chapter [Anonymization methods](#anonymization_methods).

## Set up a problem {#setup_sdcproblem}
If micro data have already been uploaded, the first step in the anonymization procedure is to create an sdc problem which can be done on this page. The layout of this page is splitted into two parts. On the left hand side, the user is presented with a table and choices that are required to define a new problem instance. On the right hand side, the user is given the possibility to explore a variable. This is useful for example to decide which variables should be used as categorical or continuous key variables. For further discussion on the choice of variables, the user should have a look at `?createSdcObj` which is the underlying function that is used to generate a problem. We now explain in detail how to proceed.

On top of the right hand sidebar the user is shown a select input field labelled `Select variable to show information` in which any of the variables from the current micro data set can be selected. By default the first variable of the data set is chosen. Below this select input a graph depending on the variable type is shown. If the selected variable is either of type `factor`, `character` or `integer` (with less or equal than 10 unique values), a barplot is shown. For variables of type `numeric` or `integer` with more than 10 unique values, a histogram showing the distribution is plotted. Below the plot, the number of unique values including `NA` is shown. Finally, below this information even more information on the selected variable is shown. In case of a continuous variable, the typical main summary statistics (Minimum, Mean, Median, Maximum and 5%-, 25%-, 75%- and 95%-quantiles) are presented while for factor variables (as well as integer variables with not more than 10 unique values), the number of occurences for each possible level is shown.

On the left hand side, an interactive table with a row for each variable available in the micro data and a total of 9 columns is shown. This table allows the user to specify relevant variables for the sdc problem. Also, it shows additional information on each variable. The variables are:

- **Variable.Name**: the variable name	
- **Type**: the class of the variable according to `class()`
- **Key**:	radio buttons with 3 choices, `no` (the default), `Cat.` and `Cont.`
    - `no`: the variable is not uses as either categorical or continuous key variable
    - `Cat.`: the variable is used as categorical key variable
    - `Cont.`: the variable is used as continuous key variable
- **Weight**:	the variable that contains sampling weights (if any)
- **Cluster.ID**: the variable that identifies clusters (for example households)
- **Remove**: variables that should be excluded when setting up the sdc problem.
- **nrCodes**: the number of unique values in the variable
- **nrNA**: number of missing values in the variable

For columns `Weight`, `Cluster.ID` and `Remove`, checkboxes are present in the table. These checkboxes are by default not selected. The checkboxes can be enabled by clicking on them. While there can at most be one variable selected as weight variable and variable holding cluster ids, multiple variables may be checked in column `Remove`. 

Below the table, two slider inputs are shown. The first one, labelled `Parameter "alpha"` is relevant for the frequency calculation given the categorical key variables that contain missing (`NA`) values. For this input, values between `0` and `1` (the default setting) in steps of `0.01` can be selected. We note that leaving the value at `1` leads to the same results as in versions of `sdcMicro` <= 4.7.0. For details on this parameter, please have a look at `?freqCalc`. The second slider, termed `Parameter "seed"` can take on values between `-250` and `250` in steps of `1` and is the number used to set the seed for the random number generator to ensure reproducability. By default, this value is set to `0`. We note that once the sliders are selected, values can also be increased and decreased by clicking the up and down (or left and right) keys on the keyboard.

Whenever values in either the radio buttons or the checkboxes are changed, it is internally checked if all conditions for a successful generation of a new sdc problem are fulfilled. In the case that some restrictions are violated, either a popup window containing additional information occurs or a red button with the error message is shown. The user can then change the variable settings in the table. Once all checks are passed, a blue button labelled `Setup SDC problem` appears below the two sliders. Clicking on this button creates the sdc problem. Finally, the page refreshes and the layout changes. In [Anonymization Methods](#anonymization_methods), these changes are further explained.

## Anonymization Methods {#anonymization_methods}
Once an sdc problem has been defined as described [above](#setup_sdcproblem), the layout of the page changes. It now features a left sidebar and the main content is shown at the right side of the screen. 

In the left sidebar, users can choose which kind of anonymization options they want to apply. On top of the sidebar, a button labelled `Delete SDC problem` is shown. Clicking this button allows to reset the current sdc problem. However, clicking this button does not immediately reset the problem but instead, a popup window appears. In this window the user has to confirm that the current problem should be deleted. This action will be performed, if the user click on the button labelled `Delete current problem`. If the user clicks `Dismiss`, the sdc problem remains unchanged.

Below this button, a list of radio buttons termed `What do you want to do?` is shown. By default, the first entry (`View/Analyse existing sdcProblem`) is selected, the other choices are `Anonymize categorical variables` and `Anonymize numerical variables`. Below, there is another list of radio buttons termed `Choose a Method`. The entires in this second select input depend on the choice in `What do you want to do?` and update once this input changes. Also, the content in the center of the screen is dependent on the choices in the left sidebar. We now continue to describe the possible choices for [View/Analyse existing sdcProblem](#view_analyze_existing_problem), [Anonymize categorical variables](#anonymize_categorical) and [Anonymize numerical variables](#anonymize_numerical).

In case either `Anonymize categorical variables` or `Anonymize numerical variables` is selected, the layout of the page is changed again. In this case, a sidebar on the right hand side of the page appears. In this sidebar, many useful statistics on the current anonymization process are listed below each other:

- **Important Variables**

In the first section, the *"important"* variables in the current sdc problem are listed. These are the categorical key variables, the numerical key variables (if any) as well as the variables defining sampling weights or cluster identification (if any). This information is presented in tabular format.

- **Additional Parameters** 

The second block lists - also in tabular format - the number of records in the data set within the current sdc problem instance and the value for paramters `alpha` and `random seed` that were used when setting up the current problem.

- **Risk (k-Anonymity)**

The next table shown the number and percentages of records violating `2`-, `3`- and `5`-anonymity in the current sdc problem. In parenthesis the corresponding numbers are shown for the initial sdc problem without any anonymization procedures applied.

- **Numeric Risk** 

In case that variables have been specified as numerical key variables when [setting up the sdc problem](#setup_sdcproblem), another table showing the estimated minimal and maximum risk for numeric key variables is shown for both the original and the (possibly) modified variables. For more information have a look at `?dRisk`.

- **Information Loss**

The section on information loss is also only displayed if continuous key variables are available in the current problem instance. If this is the case, the values for utility measures `IL1` and the `Difference of Eigenvalues` are shown for both the original and (possibly) modified variables. For more information have a look at `?dUtility`.

This sidebar is always updated whenever the sdc problem instance is modified which is the case when any anonymization procedure was applied. In some cases it is also extended, for example when categorical variables have been post randomized as explained in [here](#pram_simple) and [here](#pram_expert).

### [tbw] View/Analyse existing sdcProblem {#view_analyze_existing_problem}
Analyse the Problem

#### [tbw] Show Summary {#show_sdc_summary}
#### [tbw] Explore variables {#explore_sdc_vars}
This is exactly the same thing as already described in [Explore variables](#explore_inputvars), the only difference being that the analyzed variables are now those currently available in the active problem instance.

#### [tbw] Add 'Ghost'-Variables {#add_ghostvars}
#### [tbw] Create new IDs {#create_new_ids}

### Anonymize categorical variables {#anonymize_categorical}
If `Anonymize categorical variables` has been selected in `What do you want to do?` in the left sidebar of the screen, the options [Recoding](#recoding_sdcproblem), [k-Anonymity](#kanon), [Postrandomization (simple)](#pram_simple), [Postrandomization (expert)](#pram_expert) and [Supress values with high risks](#supp_highrisk) are available from the radio button list termed `Choose a Method` and will be described below.

#### [tbw] Recoding {#recoding_sdcproblem}
to be written, same as described [here](#recode_factors_inputdata), the only difference being that the analyzed variables are now those currently available in the active problem instance.

#### [tbw] k-Anonymity {#kanon}
#### Postrandomization (simple) {#pram_simple}
This page offers the possibility to randomize one or more variables based on an invariant probability transition matrix. To apply this method to the current sdc problem, the user has to choose at least one variable from the input field labelled `Select variable(s) for PRAM` in which by default no variable is selected. The user can choose in this input from any existing factor variable that has not yet been pramed in the current sdc problem. It is also possible to select one or more categorical key variables. In this case, however, any future risk-calculations cannot be reliably interpreted any longer. This warning (as well as any other possible warnings and errors, if any) are however shown to the user at the top of the page.

After selecting at least one variable, is it possible to select a variable which will be used for stratification. If the default value of `no stratification` in the select input named `Postrandomize within different groups (stratification)?` is changed, the post randomization of the selected variables is performed independently for each unique value of the selected variable. In this select field, only one variable may be selected. It should be noted, that stratification variables can be crated before setting up the sdc problem instance as it was described [here](#create_strata_var).

To create the transition matrix, two parameters (`pd` and `alpha`) need to be provided using slider inputs. `pd` refers to the minimum diagonal values in the (internally) generated transition matrix. The higher this value is chosen, the more likely it is that a value stays the same category and is not going to be changed. Parameter `alpha` allows to add some perturbation to the calculated transition matrix. The lower this number is, the less perturbed the matrix will get. By default, the value of `Choose value for 'pd'` will be `0.8` and the value of `Choose value for 'alpha'` will be `0.5`. For further details, have a look at `?pram`.

Once at least one variable that should be pramed has been selected, a button labelled `Postrandomize` appears at the bottom of the page. Pressing this button performs the postrandomization. Afterwards, the page refreshes and in the right sidebar a section called `Postrandomization` either appears or is extended. In this part of the sidebar, for each variable that has been postrandomized the number and percentages of value changes are listed.

#### Postrandomization (expert) {#pram_expert}
This page offers the possibility to randomize a variable using a freely specified transition matrix. To apply this method to the current sdc problem, the user has to choose one variable from the input field labelled `Select variable for PRAM` in which by default the first possible variable is selected. The user can choose in this input from any existing factor variable that has not yet been pramed in the current sdc problem. It is also possible to select one or more categorical key variables. In this case, however, any future risk-calculations cannot be reliably interpreted any longer. This warning (as well as any other possible warnings and errors, if any) are however shown to the user at the top of the page.

After selecting at least one variable, is it possible to select a variable which will be used for stratification. If the default value of `no stratification` in the select input named `Postrandomize within different groups (stratification)?` is changed, the post randomization of the selected variables is performed independently for each unique value of the selected variable. In this select field, only one variable may be selected. It should be noted, that stratification variables can be crated before setting up the sdc problem instance as it was described [here](#create_strata_var).

Below this inputs, an interactive table is shown. This table has to be edited by the user in a way so that it can be used as a transition matrix. For any given row, the numbers specify percentages that the current value (the actual row name) changes to the value specified by the respective colum name. By default, in the diagonal of the table, the values are `100`. This means that the probability that the value does not change is `100%`. The user can change the table in a way that the sum of the values in each row equals `100`. If this is not the case, a red button appears below the table giving instant feedback that the table needs to be further edited. Values in specific cells may be changed by clicking into the cell and entering a new values.

Once the transition matrix is valid (eg. the values in all rows sum up to `100`), a button labelled `Postrandomize` appears at the bottom of the page. Pressing this button performs the postrandomization. Afterwards, the page refreshes and in the right sidebar a section called `Postrandomization` either appears or is extended. In this part of the sidebar, for each variable that has been postrandomized the number and percentages of value changes are listed.

#### Supress values with high risks {#supp_highrisk}
On this page it is possible to set values for the most-risky records to `NA` in a categorical key variable. To do so, the user needs to select a categorical key variable from the select input labelled `Select Key-Variable for Suppression` in which by default the first key variable is already selected. The next step is to set an appropriate threshold value which will be used to identify the *"risky"* records. These records are defined as those having an individual reidentification risk larger than the selected threshold. The threshold may be changed by updating the slider input termed `Individual Risk Threshold`. The range of this slider starts at `0` and the maximum value depends on the current sdc problem.

Below this inputs, histogram showing the distribution of the individual risk values is plotted. In the graph, a vertical black line representing the current value of the threshold is also shown. Finally there is a button labelled `Supress {nr} values with high risk in variable {var}` is present. The labelling of this button is dynamic. It shows the number of records that would be set to missing in the selected variable for the current choice of the threshold. If this button is pressed, the records in the selected variable having individual risks above the threshold are set to `NA`. The view finally updates and the [Show Summary](#show_sdc_summary) page is shown where all measures have been recalculated.

### [tbw] Anonymize numerical variables {#anonymize_numerical}
#### [tbw] Top-/Bottom Coding
#### [tbw] Apply Microaggregation
#### [tbw] Adding Noise to the data
#### [tbw] Apply Rank-Swapping

# [tbw] Risk/Utility  {#risk_utility}

- If no problem instance has been specified -> `Create a SDC problem` (Anonymize page) or `Upload a previously saved problem` (Undo-page)
- Once a problem instance has been specified -> Sidebar left + Sidebar right

## [tbw] Risk measures
### [tbw] Information of Risks
### [tbw] Suda2 risk-measure
### [tbw] l-Diversity risk-measure

## [tbw] Visualizations
### [tbw] Histogram/Mosaicplot
### [tbw] Tabulations
### [tbw] Information Loss
### [tbw] Obs violating k-Anon

## [tbw] Numerical Risk Measures
### [tbw] Compare summary statistics
### [tbw] Disclosure Risk
### [tbw] Information Loss

# Export Data {#export_data}
In this tab, the GUI offers the possibiliby to export the current state of the anonymized microdata from the current problem instance to a file in various formats or save a report summarizing the anonymization process as an html-file to disk. If no problem instance has been specified, the user is informed that he needs to create a problem first. By clicking on the button labelled `Create an SDC-Problem`, the GUI changes to the [Anonymize](#anonymize) page, where the user can create a problem. As an alternative, the user may upload a previously saved problem instance. By clicking on the button `Upload a previously saved problem`, the user is taken to the [Undo](#undo) page where he may upload an previously saved problem instance.

If, however, a problem instance has been defined, the page features a sidebar on the left hand side of the screen. In this sidebar, the user can choose from either `Anonymized Data` (the default) or `Anonymization Report` by clicking on the desired text or button. 

## Anonymized Data
On this page, the micro data available at present in the active sdc problem instance after the applied anonymization techniques as described [here](#anonymization_methods) can be saved to disk. 

On top of this page, an interactive, sortable and browsable table containing showing the data that will be written to a file are shown. The variables can be sorted by clicking on the small arrows next to the variable names on top of the table. Also on the top, there is a dropdown field where users can select how many observations should be displayed on one page. On the bottom of the table the users can find a dynamic pagination field which allows users to jump to a given *"page"* of the current table.

Below the table, two sets of radio buttons are shown:

**Select file-format**

Using this input, the desired output format can be specified. The possible choices are `R-Dataset`, `SPSS-File`, `Comma-seperated File` and `STATA-File` and can be selected by clicking on the appropriate text or button. If `Comma-seperated File` is chosen, additional controls relevant for the generation of the output file appear below. These options three additional radio button inputs:

  - **First row contains variable names**: allows to specify if variable names should be written to the output file (`TRUE`) which is the default setting or not (`FALSE`)
  - **Separator**: allows to specify the seperation character, possible choices are `Semicolon (;)` (the default), `Tab` and `Comma (,)`
  - **Decimal-Character**: allows to specify the decimal character, possible choices are `Dot (.)` (the default) and `Comma (,)`

**Randomize Order of Observations**

This set of radio buttons allow to choose, if the observations in the dataset should be randomized. The possible choices are `Do not randomize` (the default). In that case, the order of records remains unchanged. If `Perform random swapping of IDs` is chosen, the records of the dataset are randomly changed. In case that a household/cluster variable has been selected when specifying the current sdc problem as described [here](setup_sdcproblem), two additional options are possible. If `Randomize by cluster/household id` is selected, the values of this identification variable are randomized across the dataset. If the user opts to choose `Randomize within cluster/household`, not only the values of the household identification variable are randomly changed but also the the order of records within the households/clusters are permuted.

Below this option, a button labelled `Save the anonymized data` is shown. Clicking this button finally creates a file named `exportedData_sdcMicro_{timestamp}.{filetype}` using `writeSafeFile()` with the specified settings in the destination folder that has been specified in the [About](#about) page or (by default) in the current working directory if this setting has not been changed.

## Anonymization Report
On this page, an anonymization report can be generated and saved to disk. The user can select the type of record that can be generated by choosing from the radio button input. If `internal (detailed)` (the default) is selected, a quite long report is generated while the resulting report if `external (short overview)` was selected just gives a very broad overview about the anonymization process. Once the selection has been done, clicking on the button labelled `Save the report` writes the report to disk. A file `sdcReport_internal_{timestamp}.html` is generated in the destination folder that has been specified in the [About](#about) page or (by default) in the current working directory if this setting has not been changed.

# Reproducibility {#reproducibility}
In this tab, users find information to be able to reproduce the anonymization steps in the command line interface. 

If no inputdata have been uploaded on the [Microdata](#upload_microdata) page, this page shows two buttons. Clicking on the button labelled `Upload microdata` sends the user to the [Microdata](#upload_microdata) section of the GUI where microdata may be uploaded. Clicking on the button below labelled `Upload a previously saved problem` navigates to the [Undo](#undo) page where a problem instance that has been saved to disk can be uploaded.

If inputdata or a problem instance are available, on the left hand side of the page a sidebar is shown. In this sidebar, users can make the choices that are described below. It is possible to view the current script (the default), import a previously exported sdc problem from disk or save the current state of the current problem instance to disk for later re-import. This option is however only possible if a problem instance has been successfully specified.

## View/Save the current script
On this page, users can view the code that has been applied so far. This code could be run in `sdcMicro` directly with the only limitation being that the file path when uploading microdata files is relative to the `fileInput()`-functionality of shiny which gives no way to return the path of the uploaded file on the local disk. So for full reproducibiliby, users may need to adjust the path listed in the current script.

Above the script output, a button labelled `Save Script to File` is shown. Clicking on this button saves the current script in a file `exportedScript_sdcMicro_{timestamp}.R` in the destination folder that has been specified in the [About](#about) page or (by default) in the current working directory if this setting has not been changed.

## Import a previously saved sdcProblem
On this page it is possible to import a previously saved problem instance to the GUI. Once the user clicks on the `Browse` button, he may locate any previously exported problem instance. The file chooser only allows to upload `.rdata` files to minimize possible mistakes. Once the file has been located and the `Open` button is pressed, the selected file is loaded into the GUI. If the import was successful, the content of the GUI has been replaced with the data from the imported file.

If the import was not successful, the user is presented with the resulting error message and a button labelled `Try again!`. After clicking this button, it is possible to upload a different file. If the import of the problem instance worked, the GUI changes to the overview of the current sdc problem instance as described [here](#setup_sdcproblem).

## Export/Save the current sdcProblem {#export_sdc_probleminstance}
This option is only shown in the sidebar once an sdc problem instance has been generated as described [here](#anonymize). If the button labelled `Save the current problem` is clicked, the entire current probleminstance (and including all GUI-relevant data) are saved to a file named `exportedProblem_{timestamp}.rdata` in the destination folder that has been specified in the [About](#about) page or (by default) in the current working directory if this setting has not been changed.

After the file has been successfully saved, the page refreshes and shows the complete path to most recent saved file at the bottom of the page.

# Undo {#undo}
This page allows the user to undo the last anonymization step. If there is no active sdc problem, the user is presented with two options. He can either click on the button labelled `Upload microdata` in case no micro data have been uploaded to the GUI or on the button `Create an SDC problem` in case that micro data are available. In the former case the page is changed to the [Microdata](#microdata) page while in the latter case it is changed to the [Anonymize](#anonymize) page. In both cases the user may also click on the `Browse` button to import a [previously saved problem instance](#export_sdc_probleminstance). We note that this functionality is always available from this page, independent on the availabilty of inputdata, an sdc problem instance or if it is possible to undo anonymization steps.

If a problem instance is available, the page layout changes. In case it is possible to undo an anonymization step, the last anonymization action that has been applied is printed on top of this page. Below there is a button termed `Undo last Step`. Clicking on this button opens a pop up window in which the user has to confirm that the last anonymization step should be revertd. In case that this button was unintentionally pressed, clicking on `Dismiss` closes the popup window and it is possible to continue with the anonymization process.

Below, this button there is another action button labelled `Save the current problem` which has exactly the same functionality as the button described [here]( {#export_sdc_probleminstance}). Once the pproblem was successfully saved to disk, the page refreshes and the path the exported file is shown.

# [tbw] Summary
