// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_calcSuppInds
List cpp_calcSuppInds(NumericMatrix inp, NumericVector checkVals);
RcppExport SEXP sdcMicro_cpp_calcSuppInds(SEXP inpSEXP, SEXP checkValsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type inp(inpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type checkVals(checkValsSEXP);
    __result = Rcpp::wrap(cpp_calcSuppInds(inp, checkVals));
    return __result;
END_RCPP
}
