# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_calcSuppInds <- function(inp, checkVals) {
    .Call('sdcMicro_cpp_calcSuppInds', PACKAGE = 'sdcMicro', inp, checkVals)
}

