# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_calcSuppInds <- function(inp, checkVals, params) {
    .Call(`_sdcMicro_cpp_calcSuppInds`, inp, checkVals, params)
}

microaggregation_argus_cpp <- function(inp, k, useOptimal) {
    .Call(`_sdcMicro_microaggregation_argus_cpp`, inp, k, useOptimal)
}

rankSwap_argus_cpp <- function(inp, perc) {
    .Call(`_sdcMicro_rankSwap_argus_cpp`, inp, perc)
}

